# Generated by Django 5.2.14 on 2026-06-01 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='الاسم')),
                ('slug', models.SlugField(blank=True, max_length=140, verbose_name='الرابط')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('icon', models.CharField(blank=True, max_length=64, verbose_name='الأيقونة')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('inactive', 'غير نشط')], default='active', max_length=8, verbose_name='الحالة')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to=settings.AUTH_USER_MODEL, verbose_name='التاجر')),
            ],
            options={
                'verbose_name': 'تصنيف',
                'verbose_name_plural': 'التصنيفات',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('slug', models.SlugField(blank=True, max_length=220, verbose_name='الرابط الداخلي')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='وصف مختصر')),
                ('description', models.TextField(blank=True, verbose_name='الوصف الكامل')),
                ('supplier_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر المورد')),
                ('suggested_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر المقترح')),
                ('affiliate_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='عمولة المسوّق')),
                ('currency', models.CharField(choices=[('SAR', 'ريال سعودي'), ('EGP', 'جنيه مصري'), ('AED', 'درهم إماراتي'), ('KWD', 'دينار كويتي'), ('USD', 'دولار أمريكي')], default='EGP', max_length=3, verbose_name='العملة')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='الكمية المتاحة')),
                ('status', models.CharField(choices=[('Active', 'نشط'), ('Draft', 'مسودة'), ('Disabled', 'معطّل')], default='Draft', max_length=8, verbose_name='الحالة')),
                ('badge', models.CharField(choices=[('Bestseller', 'الأكثر مبيعاً'), ('New', 'جديد'), ('Hot Offer', 'عرض ساخن'), ('High Profit', 'ربح مرتفع'), ('None', 'لا يوجد')], default='None', max_length=12, verbose_name='الشارة')),
                ('public_link_slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='رابط الصفحة العامة')),
                ('seo_title', models.CharField(blank=True, max_length=60, verbose_name='عنوان SEO')),
                ('seo_description', models.CharField(blank=True, max_length=160, verbose_name='وصف SEO')),
                ('video_url', models.URLField(blank=True, verbose_name='رابط الفيديو')),
                ('is_featured', models.BooleanField(default=False, verbose_name='منتج مميّز')),
                ('is_best_seller', models.BooleanField(default=False, verbose_name='الأكثر مبيعاً')),
                ('is_hot_offer', models.BooleanField(default=False, verbose_name='عرض ساخن')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='التاجر')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.productcategory', verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='products/', verbose_name='الصورة')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='النص البديل')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_main', models.BooleanField(default=False, verbose_name='الصورة الرئيسية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'صورة منتج',
                'verbose_name_plural': 'صور المنتجات',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(fields=('merchant', 'slug'), name='uniq_category_slug_per_merchant'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('merchant', 'slug'), name='uniq_product_slug_per_merchant'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('supplier_price__gte', 0)), name='chk_product_supplier_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('suggested_price__gte', 0)), name='chk_product_suggested_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('affiliate_profit__gte', 0), ('affiliate_profit__isnull', True), _connector='OR'), name='chk_product_affiliate_profit_non_negative'),
        ),
    ]
