# Generated by Django 5.2.14 on 2026-05-31 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'مستخدم', 'verbose_name_plural': 'المستخدمون'},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('MERCHANT', 'تاجر'), ('AFFILIATE', 'مسوّق بالعمولة'), ('ADMIN', 'مدير')], default='MERCHANT', max_length=16, verbose_name='الدور'),
        ),
    ]
