# Generated by Django 5.2.14 on 2026-06-01 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='الاسم الكامل')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='الجوال')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='المدينة')),
                ('country', models.CharField(blank=True, max_length=80, verbose_name='الدولة')),
                ('status', models.CharField(choices=[('Pending', 'قيد المراجعة'), ('Active', 'نشط'), ('Suspended', 'موقوف'), ('Rejected', 'مرفوض')], default='Pending', max_length=10, verbose_name='الحالة')),
                ('level', models.CharField(choices=[('Bronze', 'برونزي'), ('Silver', 'فضي'), ('Gold', 'ذهبي'), ('Platinum', 'بلاتيني')], default='Bronze', max_length=10, verbose_name='المستوى')),
                ('referral_code', models.CharField(max_length=32, unique=True, verbose_name='كود الإحالة')),
                ('coupon_code', models.CharField(blank=True, max_length=32, verbose_name='كود الخصم')),
                ('bio', models.TextField(blank=True, verbose_name='نبذة تعريفية')),
                ('social_instagram', models.CharField(blank=True, max_length=120, verbose_name='إنستغرام')),
                ('social_tiktok', models.CharField(blank=True, max_length=120, verbose_name='تيك توك')),
                ('social_facebook', models.CharField(blank=True, max_length=120, verbose_name='فيسبوك')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ القبول')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الرفض')),
                ('suspended_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإيقاف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliates', to=settings.AUTH_USER_MODEL, verbose_name='التاجر')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliate_links', to=settings.AUTH_USER_MODEL, verbose_name='حساب المسوّق')),
            ],
            options={
                'verbose_name': 'مسوّق',
                'verbose_name_plural': 'المسوّقون',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('coupon_code', ''), _negated=True), fields=('merchant', 'coupon_code'), name='uniq_coupon_per_merchant')],
            },
        ),
    ]
